// SPDX-License-Identifier: AGPL-3.0-or-later

import { z } from "zod";
import { PutObjectCommand } from "@aws-sdk/client-s3";
import { randomUUID } from "crypto";
import { defineTool } from "@polyant-ai/plugin-sdk";
import { errMsg } from "../../utils/error.js";
import { extensionFromMime } from "../../utils/mime.js";
import { describeAgentS3Failure, resolveAgentS3 } from "../../attachments/agent-s3.js";

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB

export default defineTool({
  name: "fileUpload",
  description:
    "Upload a file to S3 and return its key and URL.\n" +
    "Use to persist attachments received from the user or files generated by other tools in the instance's S3 bucket.\n" +
    "Files are stored under `{instanceId}/{conversationId}/{filename}`.\n" +
    "Upload a current message attachment (`attachmentIndex`) or raw base64 data (`base64Data`).\n" +
    "Returns the S3 key and a URL. Limit: 10 MB.\n" +
    "Requires `s3_bucket_name` and `aws_region`, plus EITHER static keys\n" +
    "(`aws_access_key_id` + `aws_secret_access_key`) OR the explicit\n" +
    "`s3_use_task_role` opt-in, which reaches the runtime identity (the ECS task\n" +
    "role) instead. Set `s3_endpoint` for an S3-compatible server (MinIO, R2).",
  category: "storage",
  // Only the bucket and the region are unconditional: the credentials are one of
  // two shapes, and `attachments/agent-s3.ts` decides which. Everything else is
  // `optional: true` — a bare string normalizes to a REQUIRED spec, and the
  // supervisor hides a tool whose required secrets are unset, so declaring the
  // credential keys unconditionally would hide `fileUpload` from every agent
  // (no agent can hold both static keys AND the task-role opt-in).
  requiredSecrets: [
    "s3_bucket_name",
    "aws_region",
    {
      key: "aws_access_key_id",
      type: "text",
      label: "AWS access key ID",
      description:
        "Opzionale. Va impostato insieme ad aws_secret_access_key. Se assenti entrambi, abilita s3_use_task_role per usare il task role.",
      optional: true,
      sensitive: true,
    },
    {
      key: "aws_secret_access_key",
      type: "text",
      label: "AWS secret access key",
      description: "Opzionale. Va impostato insieme ad aws_access_key_id (credenziali statiche).",
      optional: true,
      sensitive: true,
    },
    {
      key: "s3_use_task_role",
      type: "text",
      label: "Usa il task role (opt-in)",
      description:
        "Opt-in esplicito ('true'/'1'/'yes'): senza chiavi statiche, usa l'identità di runtime (task role ECS) per l'accesso S3 (anche cross-account via bucket policy). Off = niente uso implicito del task role.",
      optional: true,
      sensitive: false,
    },
    {
      key: "s3_endpoint",
      type: "text",
      label: "Endpoint S3-compatibile",
      description:
        "Opzionale. URL di un server S3-compatibile (MinIO, Cloudflare R2). Se impostato, il client passa ad addressing path-style.",
      optional: true,
      sensitive: false,
    },
  ],
  inputExamples: [
    {
      label: "Upload first attachment",
      input: { attachmentIndex: 0, base64Data: null, mimeType: null, filename: null },
    },
  ],
  parameters: z.object({
    attachmentIndex: z
      .number()
      .int()
      .min(0)
      .nullable()
      .describe("Index of the attachment to upload (0-based). Use this OR `base64Data`."),
    base64Data: z
      .string()
      .nullable()
      .describe("File data encoded as base64 (alternative to `attachmentIndex`)."),
    mimeType: z
      .string()
      .nullable()
      .describe("MIME type of the file (required when using `base64Data`)."),
    filename: z
      .string()
      .nullable()
      .describe("Custom filename. If omitted, uses the attachment name or generates a UUID."),
  }),
  execute: async (
    {
      attachmentIndex,
      base64Data,
      mimeType,
      filename,
    }: {
      attachmentIndex: number | null;
      base64Data: string | null;
      mimeType: string | null;
      filename: string | null;
    },
    ctx,
  ) => {
      // One resolver, shared with attachment persistence
      // (`attachments/agent-s3.ts`): an agent has ONE bucket, and two copies of
      // "how do I reach it" is how they come to disagree. It also brings the
      // `s3_use_task_role` opt-in this tool's own description already promised,
      // and the `s3_endpoint` that MinIO and R2 need.

      // Resolve file data
      let fileBuffer: Buffer;
      let fileMime: string | undefined = mimeType ?? undefined;
      let fileName: string | undefined = filename ?? undefined;

      if (attachmentIndex != null) {
        const attachment = ctx.attachments?.[attachmentIndex];
        if (!attachment) {
          return { error: `No attachment found at index ${attachmentIndex}.` };
        }
        if (!attachment.data) {
          return { error: `Attachment at index ${attachmentIndex} has no binary data.` };
        }
        fileBuffer = attachment.data;
        fileMime = fileMime ?? attachment.mimeType;
        fileName = fileName ?? attachment.fileName;
      } else if (base64Data) {
        try {
          fileBuffer = Buffer.from(base64Data, "base64");
        } catch {
          return { error: "Failed to decode base64 data." };
        }
      } else {
        return { error: "No file provided: specify `attachmentIndex` or `base64Data`." };
      }

      // Size check
      if (fileBuffer.length > MAX_FILE_SIZE) {
        return {
          error: `File too large: ${(fileBuffer.length / (1024 * 1024)).toFixed(1)} MB (max 10 MB).`,
        };
      }

      // Build S3 key
      const ext = extensionFromMime(fileMime);
      // Sanitize filename: strip path separators to prevent key injection
      const rawName = fileName ?? `${randomUUID()}.${ext}`;
      const resolvedName = rawName.replace(/[/\\]/g, "_");
      const conversationId = ctx.conversationId ?? "unknown";
      const s3Key = `${ctx.instanceId}/${conversationId}/${resolvedName}`;

      // Read secrets
      const region = ctx.secrets?.["aws_region"];
      const resolution = resolveAgentS3(ctx.secrets);
      if (!resolution.ok) {
        return { error: `S3 not configured for this agent: ${describeAgentS3Failure(resolution)}.` };
      }
      const { client, bucket, credentialSource } = resolution.config;

      try {
        await client.send(
          new PutObjectCommand({
            Bucket: bucket,
            Key: s3Key,
            Body: fileBuffer,
            ContentType: fileMime ?? "application/octet-stream",
          }),
        );

        // Percent-encode each key segment for the DISPLAY url (the raw `s3Key`
        // went to S3 unchanged — the SDK encodes it for the API). Without this
        // a filename carrying #, ? or a space returns a link nobody can open.
        const encodedKey = s3Key.split("/").map(encodeURIComponent).join("/");
        // A custom endpoint means an S3-compatible server addressed path-style,
        // so the AWS virtual-host URL would point at a host that does not exist.
        const endpoint = ctx.secrets?.["s3_endpoint"]?.trim();
        const url = endpoint
          ? `${endpoint.replace(/\/$/, "")}/${bucket}/${encodedKey}`
          : `https://${bucket}.s3.${region}.amazonaws.com/${encodedKey}`;

        ctx.audit.log({
          action: "storage.fileUpload",
          details: {
            bucket,
            key: s3Key,
            sizeBytes: fileBuffer.length,
            mimeType: fileMime,
            credentialSource,
          },
          success: true,
        });

        // Persist the most-recently uploaded file in conversation state so a later
        // turn can reuse its URL deterministically (text-only history would drop it).
        ctx.state?.set("lastUploadedFile", {
          key: s3Key,
          url,
          sizeBytes: fileBuffer.length,
          mimeType: fileMime ?? null,
        });

        return {
          key: s3Key,
          url,
          sizeBytes: fileBuffer.length,
        };
      } catch (err) {
        const message = errMsg(err);
        console.error(`fileUpload tool error: ${message}`);
        ctx.audit.log({
          action: "storage.fileUpload",
          details: { bucket, key: s3Key, credentialSource },
          success: false,
          error: message,
        });
        return { error: message };
      }
  },
});
