// SPDX-License-Identifier: AGPL-3.0-or-later

import { z } from "zod";
import { S3Client, PutObjectCommand } from "@aws-sdk/client-s3";
import { randomUUID } from "crypto";
import { registerTool, type ToolContext } from "./registry.js";
import { errMsg } from "../../utils/error.js";
import { extensionFromMime } from "../../utils/mime.js";

const MAX_FILE_SIZE = 10 * 1024 * 1024; // 10 MB

registerTool({
  name: "fileUpload",
  description:
    "Upload a file to S3 and return its key and URL.\n" +
    "Use to persist attachments received from the user or files generated by other tools in the instance's S3 bucket.\n" +
    "Files are stored under `{instanceId}/{conversationId}/{filename}`.\n" +
    "Upload a current message attachment (`attachmentIndex`) or raw base64 data (`base64Data`).\n" +
    "Returns the S3 key and a publicly accessible URL. Limit: 10 MB.\n" +
    "Requires secrets: `aws_access_key_id`, `aws_secret_access_key`, `aws_region`, `s3_bucket_name`.",
  category: "storage",
  requiredSecrets: ["aws_access_key_id", "aws_secret_access_key", "aws_region", "s3_bucket_name"],
  inputExamples: [
    {
      label: "Upload first attachment",
      input: { attachmentIndex: 0, base64Data: null, mimeType: null, filename: null },
    },
  ],
  create: (ctx: ToolContext) => {
    // Cache S3 client per tool build (credentials are stable within a build)
    let s3Client: S3Client | null = null;
    function getClient(): S3Client | null {
      const accessKeyId = ctx.secrets?.["aws_access_key_id"];
      const secretAccessKey = ctx.secrets?.["aws_secret_access_key"];
      const region = ctx.secrets?.["aws_region"];
      if (!accessKeyId || !secretAccessKey || !region) return null;
      if (!s3Client) {
        s3Client = new S3Client({ region, credentials: { accessKeyId, secretAccessKey } });
      }
      return s3Client;
    }

    return ({
    parameters: z.object({
      attachmentIndex: z
        .number()
        .int()
        .min(0)
        .nullable()
        .describe("Index of the attachment to upload (0-based). Use this OR `base64Data`."),
      base64Data: z
        .string()
        .nullable()
        .describe("File data encoded as base64 (alternative to `attachmentIndex`)."),
      mimeType: z
        .string()
        .nullable()
        .describe("MIME type of the file (required when using `base64Data`)."),
      filename: z
        .string()
        .nullable()
        .describe("Custom filename. If omitted, uses the attachment name or generates a UUID."),
    }),
    execute: async ({
      attachmentIndex,
      base64Data,
      mimeType,
      filename,
    }: {
      attachmentIndex: number | null;
      base64Data: string | null;
      mimeType: string | null;
      filename: string | null;
    }) => {
      // Resolve file data
      let fileBuffer: Buffer;
      let fileMime: string | undefined = mimeType ?? undefined;
      let fileName: string | undefined = filename ?? undefined;

      if (attachmentIndex != null) {
        const attachment = ctx.attachments?.[attachmentIndex];
        if (!attachment) {
          return { error: `No attachment found at index ${attachmentIndex}.` };
        }
        if (!attachment.data) {
          return { error: `Attachment at index ${attachmentIndex} has no binary data.` };
        }
        fileBuffer = attachment.data;
        fileMime = fileMime ?? attachment.mimeType;
        fileName = fileName ?? attachment.fileName;
      } else if (base64Data) {
        try {
          fileBuffer = Buffer.from(base64Data, "base64");
        } catch {
          return { error: "Failed to decode base64 data." };
        }
      } else {
        return { error: "No file provided: specify `attachmentIndex` or `base64Data`." };
      }

      // Size check
      if (fileBuffer.length > MAX_FILE_SIZE) {
        return {
          error: `File too large: ${(fileBuffer.length / (1024 * 1024)).toFixed(1)} MB (max 10 MB).`,
        };
      }

      // Build S3 key
      const ext = extensionFromMime(fileMime);
      // Sanitize filename: strip path separators to prevent key injection
      const rawName = fileName ?? `${randomUUID()}.${ext}`;
      const resolvedName = rawName.replace(/[/\\]/g, "_");
      const conversationId = ctx.conversationId ?? "unknown";
      const s3Key = `${ctx.instanceId}/${conversationId}/${resolvedName}`;

      // Read secrets
      const bucket = ctx.secrets?.["s3_bucket_name"];
      const region = ctx.secrets?.["aws_region"];
      const client = getClient();

      if (!client || !bucket || !region) {
        return { error: "S3 credentials not fully configured for this instance." };
      }

      try {
        await client.send(
          new PutObjectCommand({
            Bucket: bucket,
            Key: s3Key,
            Body: fileBuffer,
            ContentType: fileMime ?? "application/octet-stream",
          }),
        );

        const url = `https://${bucket}.s3.${region}.amazonaws.com/${s3Key}`;

        ctx.audit.log({
          action: "storage.fileUpload",
          details: {
            bucket,
            key: s3Key,
            sizeBytes: fileBuffer.length,
            mimeType: fileMime,
          },
          success: true,
        });

        return {
          key: s3Key,
          url,
          sizeBytes: fileBuffer.length,
        };
      } catch (err) {
        const message = errMsg(err);
        console.error(`fileUpload tool error: ${message}`);
        ctx.audit.log({
          action: "storage.fileUpload",
          details: { bucket, key: s3Key },
          success: false,
          error: message,
        });
        return { error: message };
      }
    },
  });
  },
});
