// SPDX-License-Identifier: AGPL-3.0-or-later

import { and, like, not, notInArray, or } from "drizzle-orm";
import { getToolRegistry, requiredSecretKeys } from "./registry.js";
import { db } from "../../database/client.js";
import { tools } from "./tools.schema.js";
import { instanceTools } from "../../instances/instance-tools.schema.js";

/**
 * Set of tool names that are considered "global" — always available to every
 * instance regardless of per-instance tool configuration.
 *
 * Includes both current and future (post-rename) names so the sync works
 * across the Fase 1 → Fase 4 transition.
 */
const GLOBAL_TOOLS = new Set<string>([]);

/**
 * Upsert every tool from the in-memory registry into the `tools` DB table,
 * and hard-delete rows for tools that no longer exist in the registry.
 */
export async function syncToolsToDb(): Promise<void> {
  const registry = getToolRegistry();
  const registryNames: string[] = [];

  await db.transaction(async (tx) => {
    for (const [name, def] of registry) {
      registryNames.push(name);

      // DB stores only the flat list of secret keys (jsonb string[]). The richer
      // shape (type/choices/label/...) lives in-memory in the registry and is
      // exposed via the API — no need to persist it.
      const secretKeys = requiredSecretKeys(def.requiredSecrets);

      await tx
        .insert(tools)
        .values({
          name,
          description: def.description,
          category: def.category ?? "general",
          requiredSecrets: secretKeys,
          isMeta: def.metaTool ?? false,
          isGlobal: GLOBAL_TOOLS.has(name),
          isHarness: def.harness ?? false,
        })
        .onConflictDoUpdate({
          target: tools.name,
          set: {
            description: def.description,
            category: def.category ?? "general",
            requiredSecrets: secretKeys,
            isMeta: def.metaTool ?? false,
            isGlobal: GLOBAL_TOOLS.has(name),
            isHarness: def.harness ?? false,
            syncedAt: new Date(),
          },
        });
    }

    // Hard-delete tools that are no longer in the registry.
    //  (1) Flat (core, first-party) names absent from the registry: always pruned.
    //  (2) Namespaced (`<ns>:name`) plugin names absent from the registry AND not
    //      enabled on ANY instance: pruned too. The "not enabled anywhere" gate
    //      preserves the original safety — a plugin that transiently fails to load
    //      (version skew, PLUGIN_DIRS unmounted, import crash) but whose tools a
    //      customer had enabled still has instance_tools rows, so it is KEPT and no
    //      FK cascade wipes the enablement. Only truly orphaned rows (a merged/
    //      removed tool nobody references, e.g. `innova:aggiornaBollettaCrm`) are
    //      pruned instead of lingering as inert catalog clutter forever.
    //      Virtual `agent:*` rows are excluded here — they legitimately have no
    //      registry entry and are managed by syncAgentTool().
    // ponytail: an unreferenced plugin tool pruned during a transient load failure
    // is regenerated by the upsert on the next healthy boot — self-healing, only a
    // brief catalog gap. Add a soft-disable column if that gap ever matters.
    if (registryNames.length > 0) {
      // tool ids enabled on any instance — never prune these (see (2) above).
      const enabledRows = await tx.select({ id: instanceTools.toolId }).from(instanceTools);
      const enabledToolIds = enabledRows.map((r) => r.id);

      await tx.delete(tools).where(
        and(
          notInArray(tools.name, registryNames),
          or(
            not(like(tools.name, "%:%")),
            and(
              like(tools.name, "%:%"),
              not(like(tools.name, "agent:%")),
              enabledToolIds.length > 0 ? notInArray(tools.id, enabledToolIds) : undefined,
            ),
          ),
        ),
      );
    } else {
      // Registry empty (catastrophic load failure): preserve every namespaced row.
      await tx.delete(tools).where(not(like(tools.name, "%:%")));
    }
  });
}
