// SPDX-License-Identifier: AGPL-3.0-or-later

import { and, inArray, like, not, notInArray, or } from "drizzle-orm";
import { getToolRegistry, requiredSecretKeys, type ToolDefinition } from "./registry.js";
import { db } from "../../database/client.js";
import { tools } from "./tools.schema.js";
import { instanceTools } from "../../instances/instance-tools.schema.js";

/**
 * Set of tool names that are considered "global" — always available to every
 * instance regardless of per-instance tool configuration.
 *
 * Includes both current and future (post-rename) names so the sync works
 * across the Fase 1 → Fase 4 transition.
 */
const GLOBAL_TOOLS = new Set<string>([]);

/** The catalog row a registry definition maps to — one place, so the boot sync
 *  and the on-demand repair below can never write a row two different ways. */
function catalogRow(name: string, def: ToolDefinition) {
  return {
    name,
    description: def.description,
    category: def.category ?? "general",
    // DB stores only the flat list of secret keys (jsonb string[]). The richer
    // shape (type/choices/label/...) lives in-memory in the registry and is
    // exposed via the API — no need to persist it.
    requiredSecrets: requiredSecretKeys(def.requiredSecrets),
    isMeta: def.metaTool ?? false,
    isGlobal: GLOBAL_TOOLS.has(name),
    isHarness: def.harness ?? false,
  };
}

/**
 * Upsert every tool from the in-memory registry into the `tools` DB table,
 * and hard-delete rows for tools that no longer exist in the registry.
 */
export async function syncToolsToDb(): Promise<void> {
  const registry = getToolRegistry();
  const registryNames: string[] = [];

  await db.transaction(async (tx) => {
    for (const [name, def] of registry) {
      registryNames.push(name);
      const row = catalogRow(name, def);

      await tx
        .insert(tools)
        .values(row)
        .onConflictDoUpdate({
          target: tools.name,
          set: { ...row, syncedAt: new Date() },
        });
    }

    // Hard-delete tools that are no longer in the registry.
    //  (1) Flat (core, first-party) names absent from the registry: always pruned.
    //  (2) Namespaced (`<ns>:name`) plugin names absent from the registry AND not
    //      enabled on ANY instance: pruned too. The "not enabled anywhere" gate
    //      preserves the original safety — a plugin that transiently fails to load
    //      (version skew, PLUGIN_DIRS unmounted, import crash) but whose tools a
    //      customer had enabled still has instance_tools rows, so it is KEPT and no
    //      FK cascade wipes the enablement. Only truly orphaned rows (a merged/
    //      removed tool nobody references, e.g. `innova:aggiornaBollettaCrm`) are
    //      pruned instead of lingering as inert catalog clutter forever.
    //      Virtual `agent:*` rows are excluded here — they legitimately have no
    //      registry entry and are managed by syncAgentTool().
    // ponytail: an unreferenced plugin tool pruned during a transient load failure
    // is regenerated by the upsert on the next healthy boot — self-healing, only a
    // brief catalog gap. Add a soft-disable column if that gap ever matters.
    if (registryNames.length > 0) {
      // tool ids enabled on any instance — never prune these (see (2) above).
      const enabledRows = await tx.select({ id: instanceTools.toolId }).from(instanceTools);
      const enabledToolIds = enabledRows.map((r) => r.id);

      await tx.delete(tools).where(
        and(
          notInArray(tools.name, registryNames),
          or(
            not(like(tools.name, "%:%")),
            and(
              like(tools.name, "%:%"),
              not(like(tools.name, "agent:%")),
              enabledToolIds.length > 0 ? notInArray(tools.id, enabledToolIds) : undefined,
            ),
          ),
        ),
      );
    } else {
      // Registry empty (catastrophic load failure): preserve every namespaced row.
      await tx.delete(tools).where(not(like(tools.name, "%:%")));
    }
  });
}

/**
 * Resolve catalog ids for `names`, materializing any row the REGISTRY holds and
 * the catalog is missing. Returns name → id; a name in neither is absent from
 * the map, and the caller refuses it.
 *
 * This exists because the two sides of the Tools tab read different sources: the
 * list offers what the registry holds, the write resolves ids through the
 * catalog. The catalog is a mirror maintained at boot, so any drift turned every
 * enable of an affected tool into a SILENT no-op — the insert resolved zero ids,
 * the endpoint answered 200, and the panel reported a successful save with every
 * switch back to off. (Drift is not hypothetical: one boot whose registry lost
 * the core tools prunes every flat catalog row, and `instance_tools.tool_id`
 * cascades, so the agents lose the enablement too.)
 *
 * Repairing the mirror here — rather than only refusing — keeps "the registry is
 * the authority, the catalog is its mirror" true at the moment the disagreement
 * is discovered, instead of requiring a reboot to make the panel honest again.
 */
export async function resolveCatalogToolIds(
  names: readonly string[],
): Promise<Map<string, string>> {
  if (names.length === 0) return new Map();

  const select = async (wanted: readonly string[]) =>
    wanted.length === 0
      ? []
      : await db
          .select({ id: tools.id, name: tools.name })
          .from(tools)
          .where(inArray(tools.name, [...wanted]));

  const byName = new Map((await select(names)).map((r) => [r.name, r.id]));

  // Missing rows the registry can rebuild. A name the registry does not hold
  // either (a stale `agent:{slug}` the channel no longer publishes, a tool that
  // was removed) is deliberately left unresolved.
  const registry = getToolRegistry();
  const repairable = names.filter((name) => !byName.has(name) && registry.has(name));
  if (repairable.length === 0) return byName;

  for (const name of repairable) {
    const def = registry.get(name)!;
    await db
      .insert(tools)
      .values(catalogRow(name, def))
      .onConflictDoNothing({ target: tools.name });
  }

  for (const row of await select(repairable)) byName.set(row.name, row.id);
  return byName;
}
